### ISSUE TITLE
There was an error connecting to host

### ISSUE THREAD

**Issue by Kiyam** [thekashifmalik/sshfsui#1]
Heya,

I've setup the software as described and when I type in terminal:
`sshfs some_server:/my_folder_on_remote /my/folder/locally`

The remote folder mounts in MacOS (14.5), but when I input the same path/server combo in the tray app I get "There was an error connecting to host" in a popup. I'm not too sure where to find more detailed error messages so am not too sure what's going wrong.

Thanks!

**Comment by thekashifmalik** [comment]
@Kiyam let me see if I can't expose more error information in that popup.

In the meantime, would you post a screenshot of how you are inputing information in the `Add target` popup? You can change the actual names and paths.

**Comment by thekashifmalik** [comment]
@Kiyam release v0.6.0 will show you the underlying command that failed.

**Comment by Kiyam** [comment]
Thanks! The error I'm getting says "Command failed: timeout 3 ssh hypatia echo ping /bin/sh: timeout: command not found"

For reference, the way I have filled in the information in the add target popup is:

- Name: hypatia-folder
- Target URL: hypatia:/share/some/path/on/hypatia
- Mount Path: /Users/kiyam/Remotes/hypatia-folder

For reference, hypatia is the name of some server defined in my ssh config file with a ssh key

**Comment by thekashifmalik** [comment]
@Kiyam ah the local system is missing the `timeout` command. I had assumed this was installed on MacOS by default (similar to linux) but it's not.

Running  `brew install coreutils`  (or making `timeout` available another way) should fix the issue.

I'm going to think about how to include this dependency long-term since `timeout` is used by `sshfsui` to prevent the infinite hanging that can occur on MacOS w/ SSHFS.

**Comment by Kiyam** [comment]
@thekashifmalik ah yes, that fixed it for me! Thanks!
